name: senetunes
description: A music flutter app.
publish_to: 'none'
version: 1.0.5+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI / Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  animations: ^2.0.11
  shimmer: ^3.0.0
  auto_animated: ^3.2.0
  animate_icons: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  popover: ^0.2.8
  flutter_vector_icons: ^2.0.0

  # State management
  provider: ^6.1.2

  # Audio
  assets_audio_player: ^3.0.6
  assets_audio_player_web: any

  # Storage & cache
  shared_preferences: ^2.3.2
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  localstorage: ^4.0.0+1

  # Network / API
  http: ^1.2.2
  dio: ^5.5.0+1
  xml2json: ^6.0.1
  archive: ^3.4.9
  tuple: ^2.0.2

  # Files / Download
  path_provider: ^2.1.4
  flutter_downloader: ^1.11.6
  permission_handler: ^11.3.1

  # Notifications & review
  flutter_local_notifications: ^17.2.1
  fluttertoast: ^8.2.8
  # ⛔️ Supprimé: "toast" 0.3.0 (API obsolète/incompatible)

  in_app_review: ^2.0.9

  # Config
  global_configuration: ^2.0.0

  # Web
  webview_flutter: ^4.8.0
  connectivity_plus: ^6.0.5
  url_launcher_web: ^2.3.3
  flutter_web_plugins:
    sdk: flutter
  flutter_offline: ^5.0.0
  another_flushbar: ^1.12.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

dependency_overrides:
  uuid: ^3.0.7
  # ⚠️ Si tu rencontres encore un conflit avec carousel_slider
  # (à cause du nouveau Material Carousel), dis-le-moi: je te donnerai
  # soit une version patchée, soit une alternative sans ce package.

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/svg/
    - assets/Splash/
    - lang/
    - assets/cfg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
